/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wo7xIXJjulM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function SimpleChat() {
  return (
    (<div key="1" className="bg-gray-950 min-h-screen p-6 text-white font-sans ">
      <div className="max-w-2xl mx-auto fixed bottom-0 left-0 right-0 m-6">
        <h1 className="text-3xl font-medium text-center">Chat with Madhukar's Digital Twin!</h1>
        <p className="mt-4 text-gray-400 text-center">
          This is an evolving AI model that has my knowledge and personality.
          <br />
          You can use this to ask questions about marketing, PLG, tech stack, and more.
        </p>
        <div className="mt-8 grid grid-cols-2 gap-4">
          <Button className="bg-gray-900 border-[0.5px] rounded-lg py-8 px-4py-8 px-4 text-wrap text-white font-light hover:bg-gray-600" variant="secondary">
           How should I think about building a PLG team?
          </Button>
          <Button className="bg-gray-900 border-[0.5px] rounded-lg py-8 px-4 text-white text-wrap font-light hover:bg-gray-600" variant="secondary">
            What is your framework to build compelling messaging?
          </Button>
          <Button className="bg-gray-900 border-[0.5px] rounded-lg py-8 px-4 text-white text-wrap font-light hover:bg-gray-600" variant="secondary">
            How do I combine PLG with Sales for an effective demand generation strategy?
          </Button>
          <Button className="bg-gray-900 border-[0.5px] rounded-lg py-8 px-4 text-white text-wrap font-light hover:bg-gray-600" variant="secondary">
            Do you have recommendations for a tech stack for a PLG company?
          </Button>
        </div>
        <div className="mt-6 flex items-center rounded-full bg-[#333] px-4 py-3">
          <Input
            className="bg-transparent flex-1 placeholder-gray-400"
            placeholder="Send a message."
            type="text" />
          <Button className="bg-transparent"><PlaneIcon className="text-gray-400 ml-2 h-5 w-5" /></Button>
        </div>
      </div>
    </div>)
  );
}

function PlaneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>)
  );
}


function PlusCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M8 12h8" />
      <path d="M12 8v8" />
    </svg>)
  );
}
